version: "3.3"

networks: 
  proxy:
    external: true

services:
  whoami:
    image: "containous/whoami"
    networks: 
     - proxy
    deploy:
     replicas: 3
     labels:
      - traefik.enable=true
      - traefik.http.routers.whoami.rule=Host(`whoami.clincicasim.com`)
      - traefik.http.routers.whoami.entrypoints=web
      - traefik.http.routers.whoami.service=whoami-service
      - traefik.http.services.whoami-service.loadbalancer.server.port=80