version: "3.3"

networks: 
  proxy:
    external: true

services:
  traefik:
    image: traefik:v2.1
    command:
      - --api.dashboard=true
      - --api.debug=true
      - --log.level=DEBUG
      - --providers.docker=true
      - --providers.docker.swarmMode=true
      - --providers.docker.watch=true
      - --providers.docker.exposedByDefault=false
      - --providers.docker.network=proxy
      - --entryPoints.web.address=:80
    ports:
      - 80:80
    networks:
      - proxy
    
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

    deploy:
      placement:
        constraints:
          - node.role == manager
      replicas: 1
      restart_policy:
        condition: on-failure
      labels:
        - traefik.enable=true
        - traefik.http.routers.traefik.rule=Host(`traefik.local`)
        - traefik.http.routers.traefik.service=api@internal
        - traefik.http.routers.traefik.entrypoints=web
        - traefik.http.routers.traefik.middlewares=auth
        - traefik.http.middlewares.auth.basicauth.users=admin:{SHA}/ouIqB9Ko7uRlGim/ZssmnuXiOY=,dev:{SHA}OgKR2V9Irxp10Rt0oE/et0Pp68A=
        - traefik.http.services.traefik-dashboard.loadbalancer.server.port=8080 # dashboard port
        
