version: "3.3"

networks: 
  proxy:
    external: true

services:
  traefik:
    image: traefik:v2.1
    command:
      - "--api.dashboard=true"
      - "--providers.docker.swarmMode=true"
      - "--providers.docker.watch=true"
      - "--providers.docker.exposedByDefault=false"
      - "--providers.docker.network=proxy"
      - "--entryPoints.web.address=:80"
    ports:
      - 80:80
    networks:
      - proxy
    
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock:ro

    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      labels:
        - traefik.enable=true
        - traefik.http.routers.traefik.rule=Host(`traefik.clinicasim.com`)
        - traefik.http.routers.traefik.service=api@internal
        - traefik.http.routers.traefik.entrypoints=web
        - traefik.http.routers.traefik.service=traefik-service
        - traefik.http.services.traefik-service.loadbalancer.server.port=8080 # dashboard port
        - traefik.http.routers.api.middlewares=auth
        - traefik.http.middlewares.auth.basicauth.users=sresimco:$2y$10$HYK1HyLngLmxbUIsG1xJpuya9NM9QdoRim0JGzXywhWr7RMb3Yt06,devsimco:$2y$10$BdypsrLq5C6tZZuY/x93g.IP3qQo2/YfuEv2nKAPL8QH9fhQEhoF2
        